language: node_js
node_js: 
  - "stable"
cache: npm
services:
  - postgresql
env:
  - DB_USER=test123 DB_PASS=testing@123 DB_NAME=wayfarer DB_HOST=127.0.0.1 DB_PORT=5432 JWT_SECRET=THISISAFAKESecret123 SALT_ROUNDS=5
before_script:
  - psql -c "create USER test123 WITH PASSWORD 'testing@123';" -U postgres
  - psql -c "create database wayfarer;" -U postgres
  - npm run migration
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: npm run coverage